### ISSUE TITLE
Design and upload team logo

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#1]
## User story
1. As a AMOS team member
2. I want / need a team logo
3. So that it can represent our project and identity

## Acceptance criteria
- [x] Design a logo in Figma
- [x] Export the logo in the required formats (svg, png)
- [x] Upload it to the repository

## Definition of done (DoD)
* A logo with the required properties/formats has been uploaded in the Deliverables/sprint-01 folder

## DoD general criteria
* The logo needs to be viewed and approved by the majority of the team members

**Comment by Sabo2k** [comment]
I believe we can close this and Issue #2? 🙂
