### ISSUE TITLE
Refactor/ bug fix frontend

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#100]
## User story

1. As a developer
2. I want to refactor the frontend
3. So that it has enhanced readability, maintainability, and scalability.

## Acceptance criteria

- [x]  Show different titles for the details page
- [x]  Change breadcrumbs of the details page to redirect to the actual ID
- [x] adjust the cases frontend logic so facades are named properly and to only have the required functions

## Definition of done (DoD)

- [x] All acceptance criteria are met.
- [x] Code has been reviewed and merged into the primary development branch.
- [x] Unit/integration tests are passing.
- [x] Related pipeline is building successfully.

## DoD general criteria

- [x] Feature has been fully implemented
- [x] Feature has been merged into the mainline
- [x] All acceptance criteria were met
- [x] Product owner approved features
- [x] All tests are passing
- [x] Developers agreed to release

**Comment by Sungonogi** [comment]
I found a way to fix the wrong breadcrumbs 
- [x] Change breadcrumbs of the details page to redirect to the actual ID

I don't really know how to do it with the titles yet
and for the renaming i will wait until the recent PRs are merged because I don't want to create merge conflicts

**Comment by Sungonogi** [comment]
Showing the different titles will be more work than I thought so I would already suggest a size 3. I just changed the estimated size I hope that is ok
