### ISSUE TITLE
State Management in frontend

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#136]
## User story

1. As a developer
2. I want to implement state management in the frontend
3. So that the application can efficiently manage and update the state of various components and provide a seamless user experience.

## Acceptance criteria

Store the following attributes in the browsers localstorage:
- [x] "lightMode" default value "false" changes depending on if the theme is the dark/light mode
- [x] "filterIssues" default "true" changes depending on if you want to filter for issues in the facilities overview page
- [x] "showCardList" default "true" changes depending on if you have the card list or event list on the facilities overview page
- [x] Pressing the corresponding buttons changes the values in the local storage
- [x] Values are remembered even after refreshing the page

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

**Comment by Sungonogi** [comment]
Since no one really wanted to do this and it might even be overkill we decided to do a budget solution using the browsers local storage. Because of this we changed the est. size to 3

**Comment by Sungonogi** [comment]
Now the values are stored in the browsers localstorage


![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/28e99395-5b53-4c1f-8b48-a06f519914e5)


and if you reload the pages these values are remembered
