### ISSUE TITLE
Add filter options for the cases page

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#154]
## User story

1. As a facility manager
2. I want / need a filter for the cases page
3. So that I can easily filter the cases based on their characteristics

## Acceptance criteria

- [x] Add a filte on top of the cases list
- [x] The filter should allow filtering of cases by priority
- [x] The filter should allow filtering of cases by type
- [x] The filter should be properly styled according to the Siemens iX design library

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

**Comment by Sungonogi** [comment]
Please so everything is similar to the #191 :
delete the "open cases page" and just always have the "cases page" and add the filter only on this site

**Comment by Sungonogi** [comment]
I accidentally closed it

**Comment by Sungonogi** [comment]
Just to note, while @Hydraneut did the majority of the work. I spent like 1 hour which can be seen in the PR https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/pull/204 to help change the buttons to toggle things to the \<ix-toggle-button\>. Before it was the \<ix-chip\> which is according to the Siemens iX guidelines not supposed to be used for user interaction.

This is how the filtering looks like with the ix-toggle-button


![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/87a87870-c766-4835-8ff3-d9296f1ad3dc)
