### ISSUE TITLE
Show actual pump data on the charts in details page

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#158]
## User story

1. As a facility developer
2. I want / need to show real pump data on the charts
3. So that the charts on details page show actual pump data depending on the facility

## Acceptance criteria

- [x] Both the Pump Chart and the Env Chart show actual data from our backend (api/timeseries)
- [x] The data depends on the facility selected

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

**Comment by Sungonogi** [comment]
As the data depended on the part from the #82 issue which depended on the #110 issue which are all not merged yet. All of this was done on the feat/xd-82 branch

**Comment by Sungonogi** [comment]
to document:
the data can be seen and it calls the backend (which calls the siemens api, that is what Jonas did with the huge connect timeseries)

![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/f435e0c7-e3f7-44fd-9096-705512ac6c48)
