### ISSUE TITLE
Add filter to facilities page and thus delete facilities with issues page

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#191]
## User story

1. As a developers
2. I want / need to change the routing of the facilities pages
3. So that it is more user friendly and consistent with the rest of the pages

## Acceptance criteria

- [x] First user lands in the overview page with facilities with issues (filter is automatically applied)
- [x] There is a button in the top right to remove/add the filter
- [x]  The Open issues button in the menu on the left is deleted
- [x] the separate page for the facilities with issues is deleted (it is always just the facilities page but you can filter)

## Definition of done (DoD)

- [x] All acceptance criteria were met
- [x] Pipeline is building successfully
- [x] Unit/integration tests are passing
- [x] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [x] Developers agreed to release
- [x] Product owner approved features
- [x] Feature has been fully implemented

**Comment by Sungonogi** [comment]
I deleted the issues page (also the button in the bar on the left and the button on the home page)) and added a button to filter. Pressing the button results in all facilities with status != 'success' to be removed (and if you press again the filter is removed). To make this have an effect I randomly generated the status value for each facility (before this it was the same for all facilities) but that can be changed when the #65 issue is done

![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/c9f4e083-cf2c-49b4-a186-fcff46a14e64)
