### ISSUE TITLE
Improve order filter design/usability

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#208]
## User story

1. As a facility manager
2. I want / need an easy-to-use and visually pleasing filter for the order
3. So that it is immediately understandable how to use this component

## Acceptance criteria

- [x] The content inside the filter is styled in such a manner that the user can easily comprehend the its role and objective

## DoD general criteria

- [x] Feature has been fully implemented
- [x] Feature has been merged into the mainline
- [x] All acceptance criteria were met
- [x] Product owner approved features
- [x] All tests are passing
- [x] Developers agreed to release

**Comment by Sungonogi** [comment]
We estimated 5 in the hope of being able to add the [Category Filter](https://ix.siemens.io/docs/controls/category-filter) which would be very cool

**Comment by Sungonogi** [comment]
I want to say that while @Hydraneut and @PatrickSchm1dt got the category filter to work, I supported them with this issue for like 2-3 hours to add the state management.

**Comment by Sungonogi** [comment]
btw the filter looks like this and is remembered even if you refresh the page


![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/e710f849-8bce-4b8a-916f-fe7151ab8ca6)
