### ISSUE TITLE
Adjust the date field in the Cases

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#231]
## User story

1. As a facility manager
2. I need the date field to be adjusted in the cases
3. So that it is more readable and user-friendly.

## Acceptance criteria

- [ ] The date field in the cases is changed to a more  readable and user-friendly format. 

## Definition of done (DoD)

- [ ] All acceptance criteria were met
- [ ] Pipeline is building successfully
- [ ] Unit/integration tests are passing
- [ ] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [ ] Developers agreed to release
- [ ] Product owner approved features
- [ ] Feature has been fully implemented

**Comment by Sungonogi** [comment]
![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/448e4e5e-1b42-47af-b594-f16b375d44f0)

**Comment by lamara11** [comment]
Closed as duplicate. already implemented
