### ISSUE TITLE
Refactor: Polish frontend code

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#243]
## User story

1. As a developed
2. I want / need a polished and clean codebase
3. So that I can work on it and analyze it easily and efficiently

## Acceptance criteria

- [ ] Rename files according to naming standards. For example, always put facilities/cases as prefix and always call it "page".
- [ ] Always use constructor instead of inject() method for dependencies.
- [ ] Standardize private/protected/readonly attributes according to the following rules: always use private if possible, always use at least protected, don't use readonly.
- [ ] Reduce code redundancy. For example, by adding a custom tailwind class for the buttons in the top right.
- [ ] Remove unnecessary code. For example, delete the unused BackButtonDirective and the unused methods.

## Definition of done (DoD)

- [ ] All acceptance criteria were met
- [ ] Pipeline is building successfully
- [ ] Unit/integration tests are passing
- [ ] Code has been reviewed and merged into the primary development branch

## DoD general criteria

- [ ] Developers agreed to release
- [ ] Product owner approved features
- [ ] Feature has been fully implemented

**Comment by Sungonogi** [comment]
Size 5 because i also did a lot of other stuff f.e. add the assigned to in the BE (you can see more in the [PR](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/pull/260))
