### ISSUE TITLE
Q&A -  30. April 2024

### ISSUE THREAD

**Issue by sn0wcat** [amosproj/amos2024ss01-xcelerator-demo-app#27]
## Will we be provided with a UI design, or should we design the app ourselves?

You will design the app yourselves using components from [ix.siemens.io](https://ix.siemens.io/). This means that generic layout components  like [Frame Application](https://ix.siemens.io/docs/controls/application-frame/application),  colors, button controls etc. are given by the framework, but you are free to move in those boundaries.

Here is an example:

[Starting point](https://stackblitz.com/edit/iryzgw?embed=1&file=src%2Fapp%2Fapplication.html)

![image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/1426617/b01fe803-545a-4aea-af5b-bf2929b700af)

## Could you resend the links to the APIs? Some of them are no longer functional.

Let's start with only one API first. The timeseries API which will have the Pump IoT data:

The documentation is available here:

https://developer.siemens.com/insights-hub/docs/apis/iot-iottimeseries/api-iottimeseries-api.html

The API to retrieve the timeseries data looks like this:

![image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/1426617/43f2d8ac-b954-44e4-8388-64f0d1b0a83c)

You need two parameters (`entityid` and `propertySetName`) to call that API. They can be programmatically retrieved from [Asset Management API](https://developer.siemens.com/insights-hub/docs/apis/advanced-assetmanagement/api-assetmanagement-api.html), but you can just look them up in the UI:

![image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/1426617/a97329ec-d4b6-47d8-980e-0d525eaa6c4e)

An example working pump PUMP_010 has entityid `41d3a3ca84694099a3f74975df46619f` and two propertySets `Environment` and `PumpData`. 

An Example call like this:

`https://castidev-operationsinsight.eu1.mindsphere.io/api/iottimeseries/v3/timeseries/95940719ab23436abce095fc03357c16/PumpData?sort=desc&limit=2000&from=2024-05-01T22:00:00.000Z&to=2024-05-02T22:00:00.000Z&select=Flow,MotorCurrent,PressureIn,PressureOut,StuffingBoxTemperature`

retrieves the pump data:

```json
[
    {
        "MotorCurrent": 49.0,
        "PressureOut": 2.98391,
        "StuffingBoxTemperature": 25.0,
        "PressureIn": 1.0,
        "_time": "2024-05-02T01:58:51.478Z",
        "Flow": 245.29
    },
    {
        "MotorCurrent": 51.0,
        "PressureOut": 3.02011,
        "StuffingBoxTemperature": 25.0,
        "PressureIn": 1.0,
        "_time": "2024-05-02T01:58:41.477Z",
        "Flow": 241.018
    },
....
```

You can create a simple NestJS Mock API which just has the GET Method with two parameters (`entityid` and `propertyset`) and which returns the data from issue #6 so that the frontend can use it. The method can return either the broken pump data (PUMP_002, or working pump data PUMP_010) using some kind of algorithm, e.g. if the sum of all ascii values in the entityid is even, return broken pump otherwise return working pump) - just replace the timestamps from the JSON file with current timestamps and you will have a perfect Mocking server. (This is what I meant with 'every API should be mocked` - the application should work also stand alone without the connection to insights hub)

##  Can we use Tailwind and NestJS?

Yes, of course.  If the question was about if Tailwind and iX work together, see [here](https://community.siemens.com/t/tailwind-css-siemens-ix/1143)

## When and how can we reach you to set up calls/reviews?

You can @sn0wcat here in the issues, otherwise per email. Just make sure that I have an invitation for a meeting in my calendar I am not really good with remembering things - I also have a lot of meetings ;)

## What exactly do you mean by "each API can be replaced with a Mocked Version"?

See above. We will start the project by using simulated data and fake (mocked) local APIs to reduce complexity of calling APIs of Products like Insights Hub.

##  Can we use a Mono Repo (Nxrepo)?
Yes - (and we already have it 😸)

## How important are Angular translations?
We don't necessary need them :)

## Should users be able to register/login?

They should be able to login. Preferably we should use an OIDC provider, like GitHub. 

##  Where can we find the pump data on the Siemens Insights Hub?

In the `Monitor` application.  Here are links to PUMP-002 and PUMP-010

[PUMP-002 Insight Hub](https://castidev-operationsinsight.eu1.mindsphere.io/explore-assets/time-series?asset=ba9361db82f4411297bdd8494ecb040f&time=1714600800000_1714687200000_local_false_Today)

[PUMP-010 Insights Hub](https://castidev-operationsinsight.eu1.mindsphere.io/explore-assets/time-series?asset=41d3a3ca84694099a3f74975df46619f&time=1714600800000_1714687200000_local_false_Today)

**Comment by sn0wcat** [comment]
@lamara11 @shahraz1998

**Comment by lamara11** [comment]
@sn0wcat  thank you for all the clarifications! 
@Sabo2k @KonsumGandalf @Hydraneut @IngoSternberg @Persists @HaruspexSan @PatrickSchm1dt  Please let us know in case you have any more questions.

**Comment by sn0wcat** [comment]
@lamara11 please add the user story for the user authentication with open id connect (OIDC)

**Comment by lamara11** [comment]
@sn0wcat  I have collected a few questions from the developers.
1. Can you review the details page? The charts are now bigger but Ingo needs some feedback / has a question about the design. You can see his question in the comments on issue 79 (https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/79)
2. What do the different Attributes of Case represent?
3. Can we add more Attributes to case?
4. What should the detail view of cases look like?
5. Time Series API:  propertySetName and EntityId (AssetId) some just return []. Can you give us examples of these that are not empty

Thanks in advance!

**Comment by lamara11** [comment]
@sn0wcat  one more question about the cases. For implementing the cases in frontend we need to understand how they look like. Are the cases like a list where the user can view details about certain cases, modify the cases, delete certain ones and add new ones?  
@Persists

**Comment by Persists** [comment]
@sn0wcat I'm still a bit unclear about the distinction between facilities and assets. In the Siemens API, is there a specific endpoint for retrieving facilities? Also, can a facility contain more than one asset or are they 1-to-1 related, so in this case we don't need to create another db table and just display assets as facilities? If there are multiple assets in one facility, is the case linked to the facility or the asset?

**Comment by Sungonogi** [comment]
As far as I understood it is fine if every facility has exactly one asset and that basically every asset is a pump for now.

Also as far as I know there is no real facility existing in the Siemens data and we should just make up our own to look good. For this I have a question:

## Basic information box

For the facilities I would like to add a basic information box which is why @lamara11  also created [this](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/77)  issue. I would like to change the attributes of a facility so we have more data to show.

Right now a facility has these attributes:
```

{  
    id: '1',  
    icon: 'battery-empty',  
    notification: '99+',  
    heading: 'totally legal waste disposal',  
    subheading: 'No shady business.com',  
    variant: FACILITY_VARIANT.SUCCESS,  
    pumps: 99,  
    location: 'Ethical Valley',  
},
```

where variant can be :
success: pump works, warning: flow sometimes drops to 0,  critical: always 0

I would like to add an attribute assetId as we will always have one asset and to thus not have a number of pumps attribute. I would suggest to replace location with street, city, country. And I think it would make sense to have a manager and his email so you can get in touch with him
```
{  
    id: '1',  
    icon: 'battery-empty',  
    notification: '99+',  
    heading: 'totally legal waste disposal',  
    subheading: 'No shady business.com',  
    variant: FACILITY_VARIANT.SUCCESS,
	assetId: '4',
	 street: 'Siemensstreet 20',
	 city: 'Erlangen',
	 country: 'Germany',
	 manager: 'Willy Water',
	 email: 'willywat@siemens.de',
},
```

Like this a facility would seem a lot more real and useful and we would actually have some information apart from the charts to show.

Would that be ok?

**Comment by sn0wcat** [comment]
we would typically model facility like an asset in asset management service as Basic Site, and that details about facility would be a static aspect, like this:

```json
{
    "assetId": "864bd1a5e7ef47e5ad10cb4538f36ed7",
    "tenantId": "castidev",
    "name": "Totally Legal Waste Disposal",
    "etag": 0,
    "externalId": "",
    "t2Tenant": null,
    "subTenant": null,
    "description": "No shady business.com\n",
    "timezone": "Europe/Berlin",
    "twinType": "performance",
    "parentId": "6167e32dc97a4cb9a750c79f9f887276",
    "typeId": "core.basicsite",
    "location": {
        "country": "Germany",
        "region": "Bavaria",
        "locality": "Erlangen",
        "streetAddress": "Siemenstr. 1",
        "postalCode": "91058",
        "longitude": 11.01,
        "latitude": 49.58
    },
    "fileAssignments": [],
    "variables": [],
    "aspects": [
"facilityDetails": {
"contactType": "Manager", "email":"blubb",  "faxNumber":"blubb", "telephoneNumber": blubb

}
],
    "locks": [],
    "hierarchyPath": [
        {
            "assetId": "6167e32dc97a4cb9a750c79f9f887276",
            "name": "castidev"
        }
    ],
    "deleted": null,
    "sharing": {
        "modes": []
    },
   
}
```

see also https://castidev-assetmanager.eu1.mindsphere.io/entity/6167e32dc97a4cb9a750c79f9f887276/details/aspects?selected=864bd1a5e7ef47e5ad10cb4538f36ed7&tab=static

**Comment by sn0wcat** [comment]
Cases (including a corresponding API) are described here:
https://developer.siemens.com/insights-hub/docs/apis/advanced-casemanagement/api-casemanagement-overview.html

**Comment by Persists** [comment]
> we would typically model facility like an asset in asset management service as Basic Site, and that details about facility would be a static aspect, like this:
> 
> ```json
> {
>     "assetId": "864bd1a5e7ef47e5ad10cb4538f36ed7",
>     "tenantId": "castidev",
>     "name": "Totally Legal Waste Disposal",
>     "etag": 0,
>     "externalId": "",
>     "t2Tenant": null,
>     "subTenant": null,
>     "description": "No shady business.com\n",
>     "timezone": "Europe/Berlin",
>     "twinType": "performance",
>     "parentId": "6167e32dc97a4cb9a750c79f9f887276",
>     "typeId": "core.basicsite",
>     "location": {
>         "country": "Germany",
>         "region": "Bavaria",
>         "locality": "Erlangen",
>         "streetAddress": "Siemenstr. 1",
>         "postalCode": "91058",
>         "longitude": 11.01,
>         "latitude": 49.58
>     },
>     "fileAssignments": [],
>     "variables": [],
>     "aspects": [
> "facilityDetails": {
> "contactType": "Manager", "email":"blubb",  "faxNumber":"blubb", "telephoneNumber": blubb
> 
> }
> ],
>     "locks": [],
>     "hierarchyPath": [
>         {
>             "assetId": "6167e32dc97a4cb9a750c79f9f887276",
>             "name": "castidev"
>         }
>     ],
>     "deleted": null,
>     "sharing": {
>         "modes": []
>     },
>    
> }
> ```
> 
> see also https://castidev-assetmanager.eu1.mindsphere.io/entity/6167e32dc97a4cb9a750c79f9f887276/details/aspects?selected=864bd1a5e7ef47e5ad10cb4538f36ed7&tab=static

alright, i understand that, but how do i now get the iot Data using this data? I guess we need a list of entityId and PropertySetNames? 

If i am right the PropertySetName internally is called aspectName.
Since all of the assets we can query only have the aspectName `connectivityStatus`.

**Comment by Persists** [comment]
@sn0wcat i got it by my own, i think i dont need a answer to that, thank you anyways
