### ISSUE TITLE
Research of fundamentals

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#3]
## User story
1. As a developer
2. I want / need to grasp the fundamental objectives and technologies behind the project idea
3. So that I can organize better my work and duties, and ask relevant information from the partner

## Acceptance criteria
* Perform initial research of the project idea
* Get an overall understanding of the technologies required

## Definition of done (DoD)
* All developers have acquired enough preliminary knowledge to decide the higher-level features they would like to work on and the technologies they will use to do so
* The partner agrees with the assessments provided by the developers and with the suggested technologies

**Comment by Sabo2k** [comment]
I believe the Definition of Done could be written as a more universal guideline, which can always be reused for all other issues 🙂 
For instance, "All Acceptance Criteria are met" or "All tests ran successfully".
