### ISSUE TITLE
Xcelerator Demo Application Information and Links - Add to CONTRIBUTING.md 

### ISSUE THREAD

**Issue by sn0wcat** [amosproj/amos2024ss01-xcelerator-demo-app#4]
## Siemens and Siemens Xcelerator

* [Siemens Xcelerator](https://xcelerator.siemens.com) - Siemens Xcelerator - Open Digital Business Platform at Siemens 
* [Developer Portal](https://developer.siemens.com) - Developer Documentation Hub for Xcelerator Products
* [Insights Hub APIs](https://developer.siemens.com/insights-hub/overview.html)
* [Typescript SDK for Insights Hub](https://developer.siemens.com/industrial-iot-open-source/mindconnect-nodejs/sdk/index.html)
* [Building X APIs](https://developer.siemens.com/building-x-openness/overview.html)
* [Siemens iX](https://ix.siemens.io) - Design System and components 

## Where to get help

* [Siemens iX Community](https://community.siemens.com/c/ix/30)
* Developer Portal - Ask the chatbot ;)

**Comment by michsien104** [comment]
Hey 👋
