### ISSUE TITLE
Frame Application Screen: Homepage (Facilities with errors)

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#44]
## User story

1. As a facility manager
2. I want / need a screen to view all the facilities having a malfunctioning asset
3. So that I can promptly request for their fixing

## Acceptance criteria

- [x] The screen needs to be connected to the correct route in the navigation bar
- [x] Upon visiting the page/screen, the facility manager sees all the facilities having a malfunctioning asset in the form of cards
- [x] The facility cards need to be displayed in a grid/flex container
- [x] Each card needs to contain some basic information about the facility, such as name, location, and number of waterpumps
- [x] Each card needs to include the name and reason for malfunctioning (error type) of all the damaged assets in the respective facility
- [x] The screen must use components from Siemens iX

## DoD general criteria

- [x] Feature has been fully implemented
- [x] Feature has been merged into the mainline
- [x] All acceptance criteria were met
- [x] Product owner approved features
- [x] All tests are passing
- [x] Developers agreed to release

## Dependencies

- Item [#48](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/48)
- Item [#47](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/47)
- Item [#45](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/45)

**Comment by IngoSternberg** [comment]
Should look like [this]( https://stackblitz.com/edit/iryzgw?file=src%2Fapp%2Fapp.component.css) stackblitz page as it is described by the IP in the issue https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/28


![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/a167161b-1765-48cf-a82b-67dd89654806)

**Comment by shahraz1998** [comment]
Removed acceptance criteria regarding adding a "create work order" directly on the facility card since it's not aligned with the IP specification anymore.
