### ISSUE TITLE
Frame Application Screen: Order Form

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#45]
## User story

1. As a facility manager
2. I want / need a screen with an order form that I can submit 
3. So that I can create repairing/maintenance orders for an asset of a certain facility

## Acceptance criteria

- [ ] The screen needs to be connected to the correct route in the navigation bar
- [ ] Upon visiting the page/screen, the facility manager sees a form
- [ ] The form needs to have the following fields, two select fields, one containing a dropdown of all the facilities, and the second one containing all the assets of the selected facility (the user's first facility is set as default), a phone field, an email field, and a textfield for additional messages. Every field except the textfield is required.
- [ ] The form must be submittable already, and its values must be displayed (f.e. in the console)
- [ ] The screen must use components from Siemens iX

## DoD general criteria

- [ ] Feature has been fully implemented
- [ ] Feature has been merged into the mainline
- [ ] All acceptance criteria were met
- [ ] Product owner approved features
- [ ] All tests are passing
- [ ] Developers agreed to release

## Dependencies

- Item [#48](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/48)
- Item [#47](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/47)

**Comment by IngoSternberg** [comment]
@shahraz1998  Patrick and I are not sure about the second dropdown form containing the assets. Right now in the testdata we created there are no assets. Since @Hydraneut and @HaruspexSan are creating more test data in this issue https://github.com/orgs/amosproj/projects/43/views/2?pane=issue&itemId=62977084 it would be good to first have defined what data a facility needs to have.

We think you are referring to these assets described in the Siemens data but we are not sure how the facilities are related to them. Is it correct that a facility must have at least one asset and can as many as it wants. And are assets like described here https://miro.com/app/board/uXjVKOVn0cI=/?moveToWidget=3458764588064757504&cot=14

**Comment by IngoSternberg** [comment]
## Definition of work orders

@shahraz1998 apart from the thing with assets I have more questions regarding work orders maybe this probably also needs to be discussed with @sn0wcat.

Right now we have just created them like this 
```
export interface IOrderMock {  
    id: string;  
    facilityId: number;  
    icon: string;  
    notification: string; // text next to the icon
    heading: string;  
    subheading: string;  
    variant: string; // success(green)/warning(yellow)/critical(orange)
}
```

You can see a lot of attributes were picked to fill the push card with content. But should we even use push cards to display these? Or is there something better on the Siemens iX [website](https://ix.siemens.io/docs/controls/card-list)
![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/030a4f50-6b8d-4038-b059-76a3dcd0b7a8)

In any case we need to make sure we collect all that data in the order form or remove attributes we don't ask for there. For example the 'heading', 'subheading' and 'notificaton' field were mostly to fill this card with content but probably don't make sense to keep.

In the Acceptance criteria Shahraz you also mentioned the following fields so we will add them to the work order data: \
phone number, email address, textfield for additional messages

We need to know if a work order has more data so f.e. a status (completed/ progressing/...could maybe be shown using a [chip](https://ix.siemens.io/docs/controls/chip))

and also the corresponding asset for the work order (in case one work order is for one asset)

Do we need a detailed view for each work order where you can see f.e. it status? Or is it enough if we just see these things on the same site without changing the url after clicking on them? Maybe using the [Flip Component](https://ix.siemens.io/docs/controls/flip) from the ix website or some other form of dropdown view?

**Comment by IngoSternberg** [comment]
Most questions were resolved in the IP meeting today. I probably overworried a little
