### ISSUE TITLE
Frame Application Screen: Facilities Overview

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#46]
## User story

1. As a facility manager
2. I want / need a screen to view all the facilities
3. So that I can have an overlook of all the buildings

## Acceptance criteria

- [x] The screen needs to be connected to the correct route in the navigation bar
- [x] Upon visiting the page/screen, the facility manager sees all the facilities in the form of cards
- [x] The facility cards need to be displayed in a grid/flex container
- [x] Each card needs to contain some basic information about the facility, such as name, location, and number of waterpumps
- [x] The screen must use components from Siemens iX

## DoD general criteria

- [x] Feature has been fully implemented
- [x] Feature has been merged into the mainline
- [x] All acceptance criteria were met
- [x] Product owner approved features
- [x] All tests are passing
- [x] Developers agreed to release

## Dependencies

- Item [#48](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/48)
- Item [#47](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/47)

**Comment by IngoSternberg** [comment]
I just added myself now because I forgot. Patrick and I wrote most of the code together

**Comment by IngoSternberg** [comment]
small because after implementing the home page this site was pretty much just copy and paste
