### ISSUE TITLE
Frame Application: Create order from facilities with errors

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#53]
## User story

1. As a facility manager
2. I want / need create work order for facilities with errors
3. So that I can create request for their repairing/maintenance

## Acceptance criteria

- [ ] Upon clicking on the "create work order" from the facility details view or the homepage with facilities that have issues, the facility manager is redirected to the work order form creation page, with fields related to the facility (such as name and location) autocompleted.
- [ ] Once the work order form has been submitted, the order appears under the facility details page under the section "Open work orders".

## DoD general criteria

- [ ] Feature has been fully implemented
- [ ] Feature has been merged into the mainline
- [ ] All acceptance criteria were met
- [ ] Product owner approved features
- [ ] All tests are passing
- [ ] Developers agreed to release

## Dependencies

- Item [#54](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/54)
- Item [#68](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/68)

**Comment by Sungonogi** [comment]
it probably makes sense to do this after the  #104 issue is done

**Comment by shahraz1998** [comment]
Duplicate of #104
