### ISSUE TITLE
Authentication: Login Page

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#55]
## User story

1. As a facility manager
2. I want / need a login page
3. So that I can securely access my facilities

## Acceptance criteria

- [x] The screen needs to be connected to the correct route.
- [x] Upon visiting the page/screen, the facility manager sees inputs for email and password.
- [x] Upon submitting the required information, when all inputs are correct, the facility manager gets redirected to the homepage. In case of wrong inputs, an error message with the text "Please check your email and password again" should appear under the form.
- [x] The screen must use components from Siemens iX.

## DoD general criteria

- [x] Feature has been fully implemented
- [x] Feature has been merged into the mainline
- [x] All acceptance criteria were met
- [x] Product owner approved features
- [x] All tests are passing
- [x] Developers agreed to release

## Dependencies

- Item [#30](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/30)

**Comment by Hydraneut** [comment]
Alex and Max: We want to try to at least make the visual page as a first start.
