### ISSUE TITLE
		Make charts bigger in details page

### ISSUE THREAD

**Issue by lamara11** [amosproj/amos2024ss01-xcelerator-demo-app#79]
## User story

1. As a facility manager
2. I want / need to have bigger charts in the details page
3. So that I can have a better view of the data of my assets

## Acceptance criteria

- [x] The Charts displayed in the details page are bigger and user friendly to view.

## DoD general criteria

- [x] Feature has been fully implemented
- [x] Feature has been merged into the mainline
- [x] All acceptance criteria were met
- [x] Product owner approved features
- [x] All tests are passing
- [x] Developers agreed to release

## Dependencies

- Item [#54](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/54)

**Comment by IngoSternberg** [comment]
I made them bigger and used a grid to make everything look okay together. Is it fine if the boxes now have different sizes (the ones at the bottom are small) or should I make all of them have the same height (which means you might have to scroll down)?

![Image](https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/assets/166606862/b7a7878b-4504-4b01-b5c9-e6b5709ed48b)

**Comment by lamara11** [comment]
In my opinion it is okay to leave them smaller. It makes sense as we adjusted the charts to be more visible but the cards are already clear in the smaller size. But let's ask Igor his opinion!
