### ISSUE TITLE
Fill in the bill of materials

### ISSUE THREAD

**Issue by shahraz1998** [amosproj/amos2024ss01-xcelerator-demo-app#8]
## User story
1. As a software developer
2. I want / need a filled up bill of materials
3. So that I know the technologies that we will use and need for our project

## Acceptance criteria
* Bill of materials including everything that the developers decide to use

## Definition of done (DoD)
* Filled up bill of materials section in the planning document

## DoD general criteria
* Everyone agrees and is satisfied with the filled up bill of materials

**Comment by sn0wcat** [comment]
@shahraz1998 lets not use any copyleft dependencies - see also https://github.com/amosproj/amos2024ss01-xcelerator-demo-app/issues/9#issuecomment-2074658997
