### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by Sabo2k** [amosproj/amos2024ss01-xcelerator-demo-app#9]
## User story
1. As a developer
2. I would like to set up the project 
3. so that we can start with the development

## Acceptance criteria

- [ ] Build Environment: [NX Repo](https://nx.dev/getting-started/intro)
- [ ] Backend: [NestJS](https://docs.nestjs.com/)
- [ ] Frontend: [Angular](https://angular.io/start)

## Definition of done (DoD)

- [ ] All Acceptance Criteria were met
- [ ] Product owner approved features
- [ ] Developers agreed to release
- [ ] Feature has been merged into main branch

**Comment by sn0wcat** [comment]
I'd expect following checks to run in the CI-CD pipeline:

on `branch/merge-request` 
- [ ] lint
- [ ] build
- [ ] test

on `main`

- [ ] lint
- [ ] build
- [ ] test

scheduled:

- check that the dependencies of the project are in the list of whitelisted dependencies (no copyleft licenses) 

e.g. like this `license-checker --csv --onlyAllow \"Apache-2.0; Apache*; BSD; BSD-2-Clause; BSD-3-Clause; ISC; MIT; Unlicense; WTFPL; CC-BY-3.0; CC0-1.0\" --production`
